name: "Centralized Code Scanning"

on: 
  merge_group:
  workflow_dispatch:
  workflow_call:
    inputs:
        # used by CodeQL to define which languages to scan
        languages:
          required: true
          type: string
        # Used by CodeQL for unique build commands
        build-command: 
          required: false
          type: string
          default: ''
        skip-codeql: 
          required: false
          type: boolean
          default: false
        skip-tfsec: 
          required: false
          type: boolean
          default: false
        skip-anchore: 
          required: false
          type: boolean
          default: false
        skip-dependency-review: 
          required: false
          type: boolean
          default: false

permissions: read-all

jobs:      
  # Automatically run TFSec 
  tfsec:
    if: ${{ inputs.skip-tfsec == false }}
    name: tfsec
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
  
  # Run CodeQL Scan        
  codeql:
    if: ${{ inputs.skip-codeql == false }}
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJSON(inputs.languages) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        
    # Autobuild attempts to build the application for CodeQL
    - name: Autobuild
      if: ${{ inputs.build-command == '' }}
      uses: github/codeql-action/autobuild@v2

    # If the Autobuild command fails, pass a build command to the workflow using 'build-command' input
    - name: Custom Build Command
      if: ${{ inputs.build-command != '' }}
      run: |
        echo "Run, Build Application using script"
        ${{ inputs.build-command }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
